parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: environment
  displayName: Environment
  type: string
  default: AAT
  values:
  - Preview
  - Dev
  - AAT
  - Sandbox
  - Test1
  - Test2
  - Demo
  - Preprod
  - Prod

- name: deviceConfiguration
  displayName: Device Configurations
  type: object
  default:
    - OS: Windows
      Browser: Chrome
      BrowserVersion: Latest
      DeviceType: Desktop
      DeviceName:
      TestCaseFilter: TestCategory!=UnsupportedBrowser

- name: prodEnvs
  displayName: Environments Using Prod Subscription
  type: object
  default:
    - Prod
    - Preprod

# Set variables once
variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-test-web
  - group: vh-preview
  - group: Saucelabs
  - group: KinlyConfiguration_Test
  - ${{ if containsValue(parameters.prodEnvs, parameters.environment) }}:
    - group: vh-prod
  - ${{ if not(containsValue(parameters.prodEnvs, parameters.environment)) }}:
    - group: vh-preview

trigger: none
pr: none
schedules:
- cron: "0 19 * * *"
  displayName: Daily midnight build
  always: true
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts_shaed
  pipelines:
  - pipeline: CI
    source: hmcts.vh-test-web

stages:
  - template: templates/vh-release.yml@templates
    parameters:
      environments:
        - ${{ parameters.environment }}
      deploymentBranch: ${{ parameters.deploymentBranch }}
      releaseParameters:
        subscription: $(env_Subscription)
        secrets_KeyVault: $(env_Secret_KeyVault)
        secrets_Subscription: $(env_Secret_Subscription)
        devOpsResource: vh_test_web
        appName: vh-test-web-$(environment)
        resourceGroup: vh-test-web-$(environment)
        testCaseFilter: TestCategory=smoketest
        dependentApps:
        - name: vh-user-api-$(environment)
          resourceGroup: vh-user-api-$(environment)
          healthEndpoint: $(user_api_url)healthcheck/health
        - name: vh-bookings-api-$(environment)
          resourceGroup: vh-bookings-api-$(environment)
          healthEndpoint: $(bookings_api_url)healthcheck/health
        - name: vh-video-api-$(environment)
          resourceGroup: vh-video-api-$(environment)
          healthEndpoint: $(video_api_url)healthcheck/health
        - name: vh-test-api-$(environment)
          resourceGroup: vh-test-api-$(environment)
          healthEndpoint: $(test_api_url)health/health
        variables:
          - group: KinlyConfiguration_Test
            env:
             - Preview
             - Dev
             - AAT
             - Sandbox
             - Test1
             - Test2
          - group: KinlyConfiguration_Test2
            env:
             - Demo
        appSettings:
          - name: ApplicationInsights:InstrumentationKey
            value: vh-core-infra-AppInsightsKey
            secret: true

          # AzureAd
          - name: AzureAd:ClientId
            value: vh-test-web-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-test-web-key
            secret: true
          - name: AzureAd:PostLogoutRedirectUri
            slot:
              deployment:
                value: $(test_web_url)logout
              active:
                value: $(test_web_url)logout
          - name: AzureAd:RedirectUri
            slot:
              deployment:
                value: $(test_web_url)home
              active:
                value: $(test_web_url)home            
          - name: AzureAd:TenantId
            value: tenantid
            secret: true

          # Testing
          - name: Testing:TestUsernameStem
            value: $(Testing:TestUsernameStem)
          - name: Testing:TestUserPassword
            value: $(Testing:TestUserPassword)

          # Kinly
          - name: KinlyConfiguration:CallbackSecret
            value: $(CallbackKey)
          - name: KinlyConfiguration:ApiSecret
            value: $(KinlyApiKey)

          # Services
          - name: Services:TestApiResourceId
            value: vh-test-api-identifieruris
            secret: true
          - name: Services:TestApiUrl
            value: $(test_api_url)
            
          # SauceLabs
          - name: Saucelabs:Username
            value: $(Saucelabs:Username)
          - name: Saucelabs:AccessKey
            value: $(Saucelabs:AccessKey)
          - name: Saucelabs:RealDeviceApiKey
            value: $(RealDeviceApiKey)     

        acceptanceTestSettings:
          # Services
          - name: Services:TestWebUrl
            slot:
              deployment:
                value: $(test_web_url)
              active:
                value: $(test_web_url)
          - name: Services:TestApiUrl
            value: $(test_api_url)
          - name: Services:TestApiResourceId
            value: vh-test-api-identifieruris
            secret: true

          # AzureAd
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: AzureAd:ClientId
            value: vh-test-web-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-test-web-key
            secret: true
          - name: AzureAd:PostLogoutRedirectUri
            slot: true
          - name: AzureAd:RedirectUri
            slot: true

          # Testing
          - name: Testing:TestUsernameStem
            value: $(Testing:TestUsernameStem)
          - name: Testing:TestUserPassword
            value: $(Testing:TestUserPassword)

          # Kinly
          - name: KinlyConfiguration:CallbackSecret
            value: $(CallbackKey)
          - name: KinlyConfiguration:ApiSecret
            value: $(KinlyApiKey)

          # SauceLabs
          - name: Saucelabs:Username
            value: $(Saucelabs:Username)
          - name: Saucelabs:AccessKey
            value: $(Saucelabs:AccessKey)
          - name: Saucelabs:RealDeviceApiKey
            value: $(RealDeviceApiKey)
        runMultiDeviceTests: true
        deviceConfiguration: ${{ parameters.deviceConfiguration }}
