---
java:
  image: 'sdshmctspublic.azurecr.io/vh/test-web:20210306.8'
  applicationPort: 8080
  replicas: 2
  ingressHost: vh-test-web.{{ .Values.global.environment }}.platform.hmcts.net
  releaseNameOverride: vh-test-web
  readinessPath: /health/liveness
  livenessPath: /health/liveness
  livenessDelay: 360
  livenessPeriod: 120
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - applicationinsights--instrumentationkey
        - kinlyconfiguration--apisecret
        - kinlyconfiguration--callbacksecret
        - kinlyconfiguration--selftestapisecret
        - testing--testuserpassword
    vh-test-web:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - azuread--clientsecret
        - azuread--clientid
  environment:
    ASPNETCORE_URLS: http://+:8080
    AZUREAD__TENANTID: "fb6e0e22-0da3-4c35-972a-9d61eb256508"
    DISABLEHTTPSREDIRECTION: true
    Logging__LogLevel__Default: debug
    Logging__LogLevel__System: debug
    Logging__LogLevel__Microsoft: debug
    SERVICES__TESTAPIRESOURCEID: https://vh-test-api.{{ .Values.global.environment }}.platform.hmcts.net
    SERVICES__TESTAPIURL: https://vh-test-api.{{ .Values.global.environment }}.platform.hmcts.net
    TESTING__TESTUSERNAMESTEM: "@hearings.reform.hmcts.net"
 