---
java:
  image: "sdshmctspublic.azurecr.io/vh/test-web:latest"
  applicationPort: 8080
  replicas: 2
  ingressHost: vh-test-web.{{ .Values.global.environment }}.platform.hmcts.net
  releaseNameOverride: vh-test-web
  readinessPath: /healthcheck/health
  livenessPath: /healthcheck/health
  livenessDelay: 360
  livenessPeriod: 120
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - applicationinsights--instrumentationkey
        - azuread--tenantid
    vh-test-web:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - azuread--clientid
        - azuread--clientsecret
        #- kinlyconfiguration--apisecret
        #- kinlyconfiguration--callbacksecret
        - saucelabs--accesskey
        - saucelabs--realdeviceapikey
        - saucelabs--username
        - testing--testusernamestem
        - testing--testuserpassword
  environment:
    ASPNETCORE_URLS: http://+:8080
    AZUREAD__POSTLOGOUTREDIRECTURI: https://vh-test-web.{{ .Values.global.environment }}.platform.hmcts.net/logout
    AZUREAD__REDIRECTURI: https://vh-test-web.{{ .Values.global.environment }}.platform.hmcts.net/home
    DISABLEHTTPSREDIRECTION: true
    MSDEPLOY_RENAME_LOCKED_FILES: 1
    SERVICES__TESTAPIRESOURCEID: https://vh-test-api.{{ .Values.global.environment }}.platform.hmcts.net
    SERVICES__TESTAPIURL: https://vh-test-api.{{ .Values.global.environment }}.platform.hmcts.net/
    Logging__LogLevel__Default: debug
    Logging__LogLevel__System: debug
    Logging__LogLevel__Microsoft: debug
